- project:
    name: CLEANUP
    dependent-name: '{name}-BUILD'
    folder: EXAMPLES
    jobs:
      - '{folder}'
      - '{folder}/{name}-PRE'
      - '{folder}/{name}-MAIN1'
      - '{folder}/{name}-MAIN2'
      - '{folder}/{name}-FINAL'

- job-template:
    name: '{folder}'
    project-type: folder

- job-template:
    name: '{folder}/{name}-PRE'
    description: '{name} PRE '
    display-name: '{name} PRE '
    builders:
      - shell: |
          #!/bin/bash
          echo "Executing..."
          sleep 2
          exit 0
    publishers:
      - trigger:
          project: "{name}-MAIN1, {name}-MAIN2"
          threshold: SUCCESS
      - join-trigger:
          publishers:
            - trigger-parameterized-builds:
              - project:
                - "{folder}/{name}-FINAL"
                trigger-with-no-params: true


- job-template:
    name: '{folder}/{name}-MAIN1'
    description: '{name} MAIN1 '
    display-name: '{name} MAIN1 '
    builders:
      - shell: |
          #!/bin/bash
          echo "Executing..."
          sleep 2
          exit 0

- job-template:
    name: '{folder}/{name}-MAIN2'
    description: '{name} MAIN2 '
    display-name: '{name} MAIN2 '
    builders:
      - shell: |
          #!/bin/bash
          echo "Executing..."
          sleep 4
          exit 1

- job-template:
    name: '{folder}/{name}-FINAL'
    description: '{name} FINAL '
    display-name: '{name} FINAL '
    builders:
      - shell: |
          #!/bin/bash
          echo "Executing..."
          sleep 2
          exit 0


